AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-brute specific exceptions
#
Layout/ArgumentAlignment:
  Exclude:
    - lib/ronin/brute/http_bruteforcer.rb
    - lib/ronin/brute/builtin/http/login.rb

# we actually need to ignore network exceptions generated while bruteforcing
Lint/SuppressedException: { Enabled: false }

Lint/EmptyBlock:
  Exclude:
    - lib/ronin/brute/builtin/ssh.rb
